# Generated by Django 5.0.2 on 2024-08-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_livro_autor_livro_autores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="coautor",
        ),
    ]
