# Generated by Django 5.1 on 2024-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_capa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
        migrations.RemoveField(
            model_name="editora",
            name="url",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
        migrations.AddField(
            model_name="editora",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
